// src/lib/reportExport.ts
// CSV + branded PDF export utilities — runs entirely in browser
// Requires: npm install jspdf jspdf-autotable

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// ── CSV ───────────────────────────────────────────────────────────────────────

export function exportCSV(filename: string, rows: Record<string, any>[]) {
  if (!rows.length) return;

  const headers = Object.keys(rows[0]);
  const csv = [
    headers.join(','),
    ...rows.map(row =>
      headers.map(h => {
        const val = row[h] ?? '';
        const str = String(val).replace(/"/g, '\\"');
        return str.includes(',') || str.includes('\n') ? `"${str}"` : str;
      }).join(',')
    ),
  ].join('\n');

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── PDF ───────────────────────────────────────────────────────────────────────

export function exportPDF(
  reportTitle: string,
  subtitle: string,
  kpis: Record<string, string | number>,
  rows: Record<string, any>[],
  filename: string
) {
  if (!rows.length) return;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const today = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  // ── Header bar ──
  doc.setFillColor(37, 99, 235); // brand blue #2563eb
  doc.rect(0, 0, pageW, 18, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('Solar Arrow', 10, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(reportTitle, pageW / 2, 12, { align: 'center' });

  doc.setFontSize(9);
  doc.text(today, pageW - 10, 12, { align: 'right' });

  // ── Subtitle ──
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.text(subtitle, 10, 24);

  // ── KPI summary boxes ──
  const kpiEntries = Object.entries(kpis);
  const maxBoxes = Math.min(kpiEntries.length, 5);
  const boxW = (pageW - 20) / maxBoxes;

  kpiEntries.slice(0, maxBoxes).forEach(([label, value], i) => {
    const x = 10 + i * boxW;

    // Box background
    doc.setFillColor(239, 246, 255); // light blue
    doc.roundedRect(x, 28, boxW - 3, 16, 2, 2, 'F');

    // Value
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(37, 99, 235);
    doc.text(String(value), x + (boxW - 3) / 2, 37, { align: 'center' });

    // Label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);
    // Humanise camelCase label
    const humanLabel = label.replace(/([A-Z])/g, ' $1').trim();
    doc.text(humanLabel, x + (boxW - 3) / 2, 42, { align: 'center' });
  });

  // ── Data table ──
  const tableHeaders = Object.keys(rows[0]).map(h =>
    h.replace(/([A-Z])/g, ' $1').trim()
  );
  const tableData = rows.map(r =>
    Object.values(r).map(v => String(v ?? ''))
  );

  autoTable(doc, {
    head: [tableHeaders],
    body: tableData,
    startY: 48,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 10, right: 10 },
  });

  // ── Footer on every page ──
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();

    doc.setFillColor(248, 250, 252);
    doc.rect(0, pageH - 8, pageW, 8, 'F');

    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Solar Arrow · sa.mktgdime.com · ${today}`,
      10,
      pageH - 3
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageW - 10,
      pageH - 3,
      { align: 'right' }
    );
  }

  doc.save(`${filename}_${new Date().toISOString().split('T')[0]}.pdf`);
}
