import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../auth/[...nextauth]/route';
import { getGoogleSheetsClient } from '@/lib/googleSheets';
import { redis } from '@/lib/redis';
import { sendOrgGroupNotification } from '@/lib/telegram';

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { enquiryId, systemCapacity, materials } = await request.json();

    if (!enquiryId || !materials || materials.length === 0) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const sheetId = (session.user as any).sheetId;
    const orgId = (session.user as any).organizationId || 'default-org';
    const sheets = await getGoogleSheetsClient();

    // Fetch enquiry details
    const enquiryResponse = await sheets.spreadsheets.values.get({
      spreadsheetId: sheetId,
      range: 'ENQUIRIES!A2:Z1000',
    });

    const enquiryRows = enquiryResponse.data.values || [];
    const enquiryRow = enquiryRows.find((row: any) => row[0] === enquiryId);

    if (!enquiryRow) {
      return NextResponse.json({ error: 'Enquiry not found' }, { status: 404 });
    }

    const customerName = enquiryRow[1] || 'Unknown';
    const bomId = `BOM-${enquiryId}`;
    const generatedDate = new Date().toISOString().split('T')[0];

    // Convert materials to JSON string
    const materialsJSON = JSON.stringify({ items: materials });

    // Create ONE row for the entire BOM
    const bomRow = [
      bomId,                          // A: bomId
      enquiryId,                      // B: enquiryId
      customerName,                   // C: customerName
      `${systemCapacity} kW`,         // D: systemCapacity
      'generated',                    // E: bomStatus
      generatedDate,                  // F: bomGeneratedDate
      session.user.email,             // G: bomGeneratedBy
      'pending',                      // H: dispatchStatus
      '',                             // I-Q: dispatch fields (empty)
      '', '', '', '', '', '', '', '', '',
      'not_started',                  // R: installationStatus
      '', '',                         // S-T: installation fields
      materialsJSON,                  // U: materialsJSON
      'not_started',                  // V: materialUtilizationStatus
      'not_applicable',               // W: materialReturnStatus
      '', '',                         // X-Y: return fields
      new Date().toISOString(),       // Z: createdAt
      '',                             // AA: updatedAt
    ];

    // Append to BOM sheet
    await sheets.spreadsheets.values.append({
      spreadsheetId: sheetId,
      range: 'BOM!A:AA',
      valueInputOption: 'USER_ENTERED',
      requestBody: {
        values: [bomRow],
      },
    });

    // Invalidate cache
    await redis.del(`org:${orgId}:boms`);

    // Send Telegram notification
    try {
      const message = `📋 *NEW BOM GENERATED*

*BOM ID:* ${bomId}
*Enquiry:* ${enquiryId}
*Customer:* ${customerName}
*System:* ${systemCapacity} kW
*Materials:* ${materials.length} line items

*Generated By:* ${session.user.email}
*Date:* ${new Date().toLocaleDateString('en-IN')}

_Ready for dispatch approval._`;

      await sendOrgGroupNotification(orgId, {
        text: message,
        parseMode: 'Markdown',
      });
    } catch (notifError) {
      console.error('Telegram notification failed:', notifError);
    }

    return NextResponse.json({
      success: true,
      bomId,
      message: 'BOM created successfully',
      itemCount: materials.length,
    });
  } catch (error: any) {
    console.error('Error creating BOM:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to create BOM' },
      { status: 500 }
    );
  }
}
